[package]
name = "rs_rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rt_rs = { path = "/home/leslie/sandbox/rust/ray-trace-port/rt_rs" }
clap = { version = "4.0.29", features = ["derive"] }
